apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flow-alex  # Your correct namespace
  name: airflow-role
rules:
  - apiGroups: [""]
    resources: ["pods", "jobs"]
    verbs: ["get", "list", "create", "delete"]  # Necessary verbs for managing pods and jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-role-binding
  namespace: flow-alex  # Your correct namespace
subjects:
  - kind: ServiceAccount
    name: airflow-worker  # Service account for Airflow worker
    namespace: flow-alex  # Namespace where the service account resides
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flow-alex
  name: job-deletion-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-deletion-role-binding
  namespace: flow-alex  # Your correct namespace
subjects:
  - kind: ServiceAccount
    name: airflow-worker  # The same service account for Airflow worker
    namespace: flow-alex  # Namespace where the service account resides
roleRef:
  kind: Role
  name: job-deletion-role
  apiGroup: rbac.authorization.k8s.io
