services:
  postgres-alex-flow:
    container_name: postgres-map-matcher
    build:
      context: .
      dockerfile: postgres/Dockerfile
    platform: linux/arm64/v8  # Ensure ARM64 architecture for M1/M2 Macs
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  map-matcher-alex-flow:
    container_name: map-matcher-alex-flow
    depends_on:
      - postgres-alex-flow
      - pulsar-alex-flow
    build:
      context: .
      dockerfile: python/Dockerfile
    env_file: ./.env
    restart: always
    networks:
      - default


  pulsar-alex-consumer:
    container_name: pulsar-alex-consumer
    depends_on:
      - postgres-alex-flow
      - pulsar-alex-flow
    build:
      context: .
      dockerfile: consumer/Dockerfile
    env_file: ./.env
    restart: always
    networks:
      - default

  pulsar-alex-flow:
    image: apachepulsar/pulsar:2.10.1
    container_name: pulsar-broker
    command: >
      bash -c "bin/pulsar standalone"
    ports:
      - "6650:6650"
      - "8080:8080" 

volumes:
  mongo_data_for_flow:
    name: mongo_data_for_flow
    external: true

networks:
  default:
    driver: bridge
