apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-map-matcher-job
spec:
  schedule: "0 12 * * *"  # Runs at 12:00 UTC every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: map-matcher
              image: flow-map-matcher-alex-flow:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure  # Ensures the pod restarts on failure
