apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-alex-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar-alex-postgres
  template:
    metadata:
      labels:
        app: pulsar-alex-postgres
    spec:
      containers:
        - name: pulsar-alex-postgres
          image: pulsar-alex-postgres:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: env
          volumeMounts:
            - name: postgres-init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init-postgres.js
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgres-data
              mountPath: /var/lib/postgresql/data/
          # resources:
          #   requests:
          #     cpu: "1" 
          #     memory: "1.5Gi" # or 512Mi
          #   limits:
          #     cpu: "2"
          #     memory: "1.5Gi"
      volumes:
        - name: postgres-init-script  
          configMap:
            name: postgres-init-script
        - name: postgres-config
          configMap:
            name: postgres-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
