apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pulsar-alex-flow
spec:
  serviceName: "pulsar-broker"  # Service that governs the StatefulSet
  replicas: 2  # Number of replicas (Pulsar brokers)
  selector:
    matchLabels:
      app: pulsar-alex-flow
  template:
    metadata:
      labels:
        app: pulsar-alex-flow
    spec:
      containers:
        - name: pulsar-broker
          image: apachepulsar/pulsar:2.10.1
          imagePullPolicy: Always
          command: ["bash", "-c", "bin/pulsar standalone"]
          ports:
            - containerPort: 6650  # Pulsar binary protocol
            - containerPort: 8080  # Pulsar HTTP API
          envFrom:
            - secretRef:
                name: env
          env:
            - name: PULSAR_MEM
              value: "-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=1024m"
            - name: PULSAR_CLIENT_OPERATION_TIMEOUT_SECONDS
              value: "60"
            - name: PULSAR_CLIENT_CONNECTION_TIMEOUT_MS
              value: "30000"
            - name: PULSAR_CLIENT_KEEPALIVE_INTERVAL_SECONDS
              value: "30"
          resources:
            requests:
              cpu: "500m" # or 500m if needed
              memory: "2Gi" # or 1.5Gi if needed
            limits:
              cpu: "2"
              memory: "2Gi"
          lifecycle:
            preStop:
              exec:
                command: ["bin/pulsar-admin", "clusters", "delete", "standalone"]
  volumeClaimTemplates:
    - metadata:
        name: pulsar-broker-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi  # Adjust the volume size as necessary
