apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-alex-consumer
  labels:
    app: pulsar-alex-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulsar-alex-consumer
  template:
    metadata:
      labels:
        app: pulsar-alex-consumer
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-pulsar
          image: curlimages/curl:7.85.0
          command:
            - sh
            - -c
            - |
              until curl -sf http://my-pulsar-broker:8080/admin/v2/brokers/health; do
                echo "Waiting for Pulsar broker..."
                sleep 5
              done
      containers:
        - name: pulsar-alex-consumer
          image: pulsar-alex-consumer:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          # resources:
          #   requests:
          #     cpu: "500m"
          #     memory: "3Gi" # or 1Gi if needed
          #   limits:
          #     cpu: "500m"
          #     memory: "3Gi" # or 1.5Gi
