# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: pulsar-alex-flow
# spec:
#   serviceName: "pulsar-broker"
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pulsar-alex-flow
#   template:
#     metadata:
#       labels:
#         app: pulsar-alex-flow
#     spec:
#       containers:
#         - name: pulsar-broker
#           image: apachepulsar/pulsar:2.10.1
#           imagePullPolicy: Always
#           command: ["bash", "-c", "bin/pulsar standalone"]
#           # command: ["bash", "-c", "bin/pulsar standalone --advertised-address localhost"]
#           ports:
#             - containerPort: 6650
#             - containerPort: 8080
#           envFrom:
#             - secretRef:
#                 name: env
#           env:
#             - name: PULSAR_MEM
#               value: "-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=1024m"
#             - name: PULSAR_CLIENT_OPERATION_TIMEOUT_SECONDS
#               value: "60"
#             - name: PULSAR_CLIENT_CONNECTION_TIMEOUT_MS
#               value: "30000"
#             - name: PULSAR_CLIENT_KEEPALIVE_INTERVAL_SECONDS
#               value: "30"
#           readinessProbe:
#             httpGet:
#               path: /admin/v2/brokers/health
#               port: 8080
#             initialDelaySeconds: 140
#             periodSeconds: 10
#             timeoutSeconds: 15
#             failureThreshold: 10
#             successThreshold: 1
#           lifecycle:
#             preStop:
#               exec:
#                 command: ["bin/pulsar-admin", "clusters", "delete", "standalone"]
#   volumeClaimTemplates:
#     - metadata:
#         name: pulsar-broker-storage
#       spec:
#         storageClassName: standard
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 10Gi
