apiVersion: v1
kind: Service
metadata:
  name: mongodb-map-matcher
spec:
  selector:
    app: mongodb-alex-flow
  ports:
    - name: mongodb-map-matcher
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP