apiVersion: v1
kind: Service
metadata:
  name: pulsar-alex-postgres
spec:
  selector:
    app: pulsar-alex-postgres
  ports:
    - name: pulsar-alex-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
